---
engines:
  csslint:
    enabled: false
  coffeelint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
        #mass_threshold: 50
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - routes/**
  - public/js/**
  - public/css/**
  - "**.js"
  - server/**
exclude_paths:
- functions/node_modules
- public/**
- docs
- test
