language: node_js
node_js:
- '6'
before_script:
- npm install -g gulp
- DEBUG=highfive:* npm start &
script: gulp
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  slack: cse112-highfive:IwXDKj8qHbdq4dw6GemuC7uL
addons:
  code_climate:
    repo_token: $CODECLIMATE_TOKEN
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < lcov.info
