language: node_js

node_js:
  - "6"

before_script:
  - npm install -g gulp

script: gulp

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN

notifications:
  slack: cse112-highfive:IwXDKj8qHbdq4dw6GemuC7uL
