language: node_js

node_js:
  - "6"

before_script:
  - npm install -g gulp

script: gulp

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN

notifications:
  slack: cse112-highfive:IwXDKj8qHbdq4dw6GemuC7uL

addons:
  code_climate:
    repo_token: $CODECLIMATE_TOKEN

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info

# safelist
branches:
  only:
  - master
