language: node_js
node_js:
  - '6'
before_script:
  # - npm install -g nightwatch gulp
  - DEBUG=highfive:* npm start &
# script:
#   - gulp
#   - nightwatch --config nightwatch.js -e chrome,ie11
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app:
    master: cse112-highfive
    dev: cse112-highfive-staging
    omnichannel: cse112-highfive-dev2
notifications:
  slack: cse112-highfive:IwXDKj8qHbdq4dw6GemuC7uL
addons:
  code_climate:
    repo_token: $CODECLIMATE_TOKEN
  sauce_connect: true
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./public/coverage/lcov.info
branches:
  only:
  - master
  - dev
  - omnichannel